// Code generated by mockery v2.30.1. DO NOT EDIT.

package usecase

import (
	mock "github.com/stretchr/testify/mock"
    types "github.com/vasapolrittideah/smokefree/apps/api/features/auth/requests"
	models "github.com/vasapolrittideah/smokefree/apps/api/models"
)

// MockAuthUsecase is an autogenerated mock type for the AuthUsecase type
type MockAuthUsecase struct {
	mock.Mock
}

type MockAuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUsecase) EXPECT() *MockAuthUsecase_Expecter {
	return &MockAuthUsecase_Expecter{mock: &_m.Mock}
}

// SignIn provides a mock function with given fields: payload
func (_m *MockAuthUsecase) SignIn(payload types.SignInRequestBody) (*Token, error) {
	ret := _m.Called(payload)

	var r0 *Token
	var r1 error
	if rf, ok := ret.Get(0).(func(types.SignInRequestBody) (*Token, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(types.SignInRequestBody) *Token); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Token)
		}
	}

	if rf, ok := ret.Get(1).(func(types.SignInRequestBody) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUsecase_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockAuthUsecase_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - payload requests.SignInRequestBody
func (_e *MockAuthUsecase_Expecter) SignIn(payload interface{}) *MockAuthUsecase_SignIn_Call {
	return &MockAuthUsecase_SignIn_Call{Call: _e.mock.On("SignIn", payload)}
}

func (_c *MockAuthUsecase_SignIn_Call) Run(run func(payload types.SignInRequestBody)) *MockAuthUsecase_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.SignInRequestBody))
	})
	return _c
}

func (_c *MockAuthUsecase_SignIn_Call) Return(_a0 *Token, _a1 error) *MockAuthUsecase_SignIn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUsecase_SignIn_Call) RunAndReturn(run func(types.SignInRequestBody) (*Token, error)) *MockAuthUsecase_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function with given fields: payload
func (_m *MockAuthUsecase) SignUp(payload types.SignUpRequestBody) (*models.Account, error) {
	ret := _m.Called(payload)

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(types.SignUpRequestBody) (*models.Account, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(types.SignUpRequestBody) *models.Account); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(types.SignUpRequestBody) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUsecase_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockAuthUsecase_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - payload requests.SignUpRequestBody
func (_e *MockAuthUsecase_Expecter) SignUp(payload interface{}) *MockAuthUsecase_SignUp_Call {
	return &MockAuthUsecase_SignUp_Call{Call: _e.mock.On("SignUp", payload)}
}

func (_c *MockAuthUsecase_SignUp_Call) Run(run func(payload types.SignUpRequestBody)) *MockAuthUsecase_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.SignUpRequestBody))
	})
	return _c
}

func (_c *MockAuthUsecase_SignUp_Call) Return(_a0 *models.Account, _a1 error) *MockAuthUsecase_SignUp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUsecase_SignUp_Call) RunAndReturn(run func(types.SignUpRequestBody) (*models.Account, error)) *MockAuthUsecase_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthUsecase creates a new instance of MockAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUsecase {
	mock := &MockAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
